# Generated by Django 3.2.6 on 2021-09-12 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('urltitle', models.SlugField(max_length=250, unique=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('subone', models.CharField(max_length=80)),
                ('subone_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('onedes', models.TextField()),
                ('refer_one', models.URLField(blank=True, null=True)),
                ('subtwo', models.CharField(blank=True, max_length=80, null=True)),
                ('subtwo_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('twodes', models.TextField(blank=True, null=True)),
                ('refer_two', models.URLField(blank=True, null=True)),
                ('subthree', models.CharField(blank=True, max_length=80, null=True)),
                ('subthree_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('threedes', models.TextField(blank=True, null=True)),
                ('refer_three', models.URLField(blank=True, null=True)),
                ('subfourth', models.CharField(blank=True, max_length=80, null=True)),
                ('subfourth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('fourthdes', models.TextField(blank=True, null=True)),
                ('refer_fourth', models.URLField(blank=True, null=True)),
                ('subfifth', models.CharField(blank=True, max_length=80, null=True)),
                ('subfifth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('fifthdes', models.TextField(blank=True, null=True)),
                ('refer_fifth', models.URLField(blank=True, null=True)),
                ('subsixth', models.CharField(blank=True, max_length=80, null=True)),
                ('subsixth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('sixthdes', models.TextField(blank=True, null=True)),
                ('refer_sixth', models.URLField(blank=True, null=True)),
                ('subseventh', models.CharField(blank=True, max_length=80, null=True)),
                ('subseventh_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('seventhdes', models.TextField(blank=True, null=True)),
                ('refer_seventh', models.URLField(blank=True, null=True)),
                ('subeigth', models.CharField(blank=True, max_length=80, null=True)),
                ('subeigth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('eigthdes', models.TextField(blank=True, null=True)),
                ('refer_eigth', models.URLField(blank=True, null=True)),
                ('subnineth', models.CharField(blank=True, max_length=80, null=True)),
                ('subnineth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('ninethdes', models.TextField(blank=True, null=True)),
                ('refer_nineth', models.URLField(blank=True, null=True)),
                ('subtenth', models.CharField(blank=True, max_length=80, null=True)),
                ('subtenth_image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('tenthdes', models.TextField(blank=True, null=True)),
                ('refer_tenth', models.URLField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('written_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
