from django.db import models
from django.db.models.fields import SlugField
from django.utils import timezone
# Create your models here.

class Blog(models.Model):
    title  = models.CharField(max_length=48, blank=False)
    urltitle = models.SlugField(max_length=48, blank=False, unique=True)
    title_image = models.ImageField(upload_to='blog',blank=True, null=True)
    subone = models.CharField(max_length=80, blank=False)
    subone_image = models.ImageField(upload_to='blog',blank=True,null=True)
    onedes = models.TextField(blank=False)
    refer_one = models.URLField(blank=True, null=True)
    subtwo = models.CharField(max_length=80, blank=True, null=True)
    subtwo_image = models.ImageField(upload_to='blog',blank=True,null=True)
    twodes = models.TextField(blank=True,null=True)
    refer_two = models.URLField(blank=True, null=True)
    subthree = models.CharField(max_length=80, blank=True, null=True)
    subthree_image = models.ImageField(upload_to='blog',blank=True,null=True)
    threedes = models.TextField(blank=True,null=True)
    refer_three = models.URLField(blank=True, null=True)
    subfourth = models.CharField(max_length=80, blank=True, null=True)
    subfourth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    fourthdes = models.TextField(blank=True,null=True)
    refer_fourth = models.URLField(blank=True, null=True)
    subfifth = models.CharField(max_length=80, blank=True, null=True)
    subfifth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    fifthdes = models.TextField(blank=True,null=True)
    refer_fifth = models.URLField(blank=True, null=True)
    subsixth = models.CharField(max_length=80, blank=True, null=True)
    subsixth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    sixthdes = models.TextField(blank=True,null=True)
    refer_sixth = models.URLField(blank=True, null=True)
    subseventh = models.CharField(max_length=80, blank=True, null=True)
    subseventh_image = models.ImageField(upload_to='blog',blank=True,null=True)
    seventhdes = models.TextField(blank=True,null=True)
    refer_seventh = models.URLField(blank=True, null=True)
    subeigth = models.CharField(max_length=80, blank=True, null=True)
    subeigth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    eigthdes = models.TextField(blank=True,null=True)
    refer_eigth = models.URLField(blank=True, null=True)
    subnineth = models.CharField(max_length=80, blank=True, null=True)
    subnineth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    ninethdes = models.TextField(blank=True,null=True)
    refer_nineth = models.URLField(blank=True, null=True)
    subtenth = models.CharField(max_length=80, blank=True, null=True)
    subtenth_image = models.ImageField(upload_to='blog',blank=True,null=True)
    tenthdes = models.TextField(blank=True,null=True)
    refer_tenth = models.URLField(blank=True, null=True)
    joined_date = models.DateTimeField(default=timezone.now,editable=False)
    written_by = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title