# Generated by Django 3.2.6 on 2021-08-16 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_eighteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_phone_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='eighteen',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\d{6}$')]),
        ),
    ]
