# Generated by Django 3.2.5 on 2021-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210820_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='address',
            name='eighteen',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=4),
        ),
    ]
