# Generated by Django 3.2.6 on 2021-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210820_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eighteen',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=4),
        ),
    ]
