# Generated by Django 3.2.6 on 2021-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolbuyorder',
            name='order_id',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
