# Generated by Django 3.2.6 on 2021-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_coolbuyorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolbuyorder',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
