# Generated by Django 3.2.6 on 2021-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_coolbuyorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolbuyorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coolbuyorder',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coolbuyorder',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
