# Generated by Django 3.2.6 on 2021-08-15 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_address_eighteen'),
        ('order', '0004_auto_20210815_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoolBuyOrder',
            new_name='Order',
        ),
    ]
