# Generated by Django 3.2.6 on 2021-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('PENDING', 'PENDING')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('IN WAY', 'IN WAY'), ('ARRIVED DESTINATION', 'ARRIVED DESTINATION'), ('RECIEVED', 'RECIEVED'), ('COMPLETED', 'COMPLETED')], default='PENDING'),
        ),
    ]
