# Generated by Django 3.2.6 on 2021-08-14 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_categories', to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contain_size', models.CharField(blank=True, max_length=50)),
                ('brand_name', models.CharField(default='Bagh', max_length=100)),
                ('swag', models.BooleanField(default=False)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('unisex', models.BooleanField(default=False)),
                ('first', models.ImageField(upload_to='items')),
                ('second', models.ImageField(upload_to='items')),
                ('third', models.ImageField(blank=True, upload_to='items')),
                ('fourth', models.ImageField(blank=True, upload_to='items')),
                ('fifth', models.ImageField(blank=True, upload_to='items')),
                ('sixth', models.ImageField(blank=True, upload_to='items')),
                ('seventh', models.ImageField(blank=True, upload_to='items')),
                ('rate', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐', max_length=5)),
                ('taken_from', models.URLField()),
                ('color', models.CharField(default='Black', max_length=30)),
                ('material', models.CharField(default='Plastic', max_length=50)),
                ('return_policy', models.CharField(default='7Days Return Policy', max_length=100)),
                ('stock', models.CharField(default='In Stock', max_length=50)),
                ('authentic', models.CharField(choices=[('✔', '✔'), ('✖', '✖')], default='✔', max_length=1)),
                ('price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('type', models.CharField(default='Cloth', max_length=100)),
                ('about', models.CharField(default='Washable', max_length=100)),
                ('offer', models.CharField(blank=True, max_length=4)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_items', to='products.categories')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategories')),
            ],
        ),
    ]
