# Generated by Django 3.2.6 on 2021-09-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='about',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='taken_from',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
