# Generated by Django 3.2.6 on 2021-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210820_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fifth',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='first',
            field=models.ImageField(upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fourth',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='second',
            field=models.ImageField(upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seventh',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sixth',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='third',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
